SITE:
    Local: '127.0.0.1:8888'
    Remote:
        Url: 'https://islandimagined.dev.islandarchives.ca'
        Path: user
PORT: 8000
BSREWRITE:
    Css:
        Match: ""
        Replace: ""
    Js:
        Match: ""
        Replace: ""
PATHS:
    Scss:
        Dir: css/scss
        FileName: app.scss
        Libraries:
            - css/libraries/guff
            - css/libraries/typeplate
    Css:
        Dir: css/compiled_css
        FileName: app.css
    Img:
        Src: img/src
        Dest: img

